import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import { useSelector } from 'react-redux'
import baseApi from '../api/BaseApi'

export default function Home({ productsForHome }) {
  const account = useSelector((state) => state.account.accountInfo)
  console.log(account)
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing <code className={styles.code}>pages/index.js</code>
        </p>

        <Link href="/sign-in">Sign In</Link>

        {account && JSON.stringify(account)}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export async function getServerSideProps(context) {
  console.log(1)
  const res = await baseApi.get('/cars/getCarsForHome')
  let productsForHome = []
  if (res.data.success) {
    productsForHome = res.data.data
  }

  return {
    props: {
      productsForHome,
    },
  }
}
